cmd/platform/main.go, internal/config/config.go, internal/config/config_test.go, internal/loader/cache.go
Sanitize configuration variable ServerURL and prevent the server to start if this value is wrong.
Recover from failed writes to Redis. Just log.
=> Sanitize configuration.ServerURL

internal/core/services/identity.go
Credential ID URL was malformed.
=> fix: Credential ID

api_ui/api.yaml, internal/api_admin/api.gen.go, internal/api_admin/server.go, internal/api_admin/server_test.go, internal/core/ports/claims_repository.go, internal/core/ports/claims_service.go, internal/core/services/claims.go, internal/repositories/claims.go
delete a credential. This delete will remove the credential nonce as well. No backup is provided with this version.
=> feat: adding delete credential

api_ui/api.yaml, internal/api_admin/api.gen.go, internal/api_admin/responses.go, internal/api_admin/server.go, internal/api_admin/server_test.go, internal/core/ports/schema_admin_service.go, internal/core/ports/schema_repository.go, internal/core/services/schema_admin.go, internal/repositories/claims.go, internal/repositories/identity_state.go, internal/repositories/mt.go, internal/repositories/revocation.go, internal/repositories/schema-inmemory.go, internal/repositories/schema.go
Basic implementation of Get All Schemas endpoint. It returns all schemas, without filtering.
=> feat: Get All Schemas endpoint

api/api.yaml, api_ui/api.yaml, internal/api/api.gen.go, internal/api/server.go, internal/api_admin/api.gen.go, internal/api_admin/server.go, internal/api_admin/server_test.go, internal/core/ports/claims_repository.go, internal/core/ports/claims_service.go, internal/core/services/claims.go, internal/repositories/claims.go, internal/repositories/tests/claims_test.go
Revoking all claims of a connection will revoke all the non revoked claims of the given connection.
The revoking claims works as a transaction, or every claim get revoked or non get revoked
=> feat: adding revoke all claims of a connection

Makefile
This solves the problem of running the command make restart-ui
=> Fix makefile restart-ui

ui/public/test-schema.json, ui/src/components/schemas/ImportSchemaForm.tsx, ui/src/components/schemas/ImportSchemaPreview.tsx, ui/src/components/schemas/JSONHighlighter.tsx, ui/src/components/schemas/SchemaDetails.tsx, ui/src/components/schemas/SchemaViewer.tsx, ui/src/styles/index.scss, ui/src/utils/adapters.ts, ui/src/utils/constants.ts
There are no functional changes, only 2 new reusable components.
=> DRYing up schema details & preview.

api_ui/api.yaml, internal/api_admin/api.gen.go, internal/api_admin/server.go, internal/api_admin/server_test.go
endpoint to get if the issuer has pending actions to publish
=> feat: adding state status endpoint

api/api.yaml, internal/api/api.gen.go, internal/api/server.go, internal/core/ports/claims_service.go, internal/core/services/proof.go, internal/repositories/claims.go, internal/repositories/tests/claims_test.go
=> Escape SQL params when searching over credentials

internal/api_admin/server_test.go, internal/repositories/link_repository.go, internal/repositories/tests/link_test.go
=> fix get links endpoint when filtering by exceeded

api_ui/api.yaml, go.mod, go.sum, internal/api_admin/api.gen.go, internal/api_admin/responses.go, internal/api_admin/server.go, internal/api_admin/server_test.go, internal/core/domain/link.go, internal/core/ports/link_service.go, internal/core/services/link.go, internal/core/services/tests/link_test.go, internal/repositories/link_repository.go, internal/repositories/tests/claims_test.go, internal/repositories/tests/link_test.go
Removed validation of link credential subject parameters. Will be added back in next PR
=> feat: adding multi depth credential subject

go.mod, go.sum, internal/api_admin/server.go, internal/api_admin/server_test.go, internal/common/helpers.go, internal/common/helpers_test.go, internal/core/services/link.go, internal/jsonschema/schema.go, internal/jsonschema/schema_test.go
This PR enables the link credential subject validation against the provided schema
=> feat: validate link credential subject against schema

ui/deployment/nginx.conf
* this code exclude `/credentials/scan-link/` from nginx basic auth
=> feat: exclude link path

ui/src/components/credentials/IssueCredential.tsx, ui/src/components/issuer-state/IssuerState.tsx, ui/src/contexts/IssuerState.tsx
=> Issuer state flow

ui/src/adapters/api/connections.ts, ui/src/adapters/api/credentials.ts, ui/src/adapters/api/index.ts, ui/src/adapters/api/issuer-state.ts, ui/src/adapters/api/schemas.ts, ui/src/adapters/parsers/index.ts, ui/src/components/connections/ConnectionsTable.tsx, ui/src/components/credentials/IssuanceMethodForm.tsx, ui/src/components/credentials/LinksTable.tsx, ui/src/components/issuer-state/IssuerState.tsx, ui/src/components/schemas/SchemasTable.tsx, ui/src/domain/connection.ts, ui/src/utils/types.ts
=> Add zod support to buildAPIError and parse elements of lists individually

ui/src/adapters/parsers/forms.ts, ui/src/components/credentials/IssuanceMethodForm.tsx, ui/src/components/credentials/IssueCredential.tsx, ui/src/components/credentials/SelectSchema.tsx, ui/src/components/schemas/SchemaDetails.tsx, ui/src/components/schemas/SchemasTable.tsx, ui/src/routes.ts, ui/src/utils/constants.ts
=> feat: sync selectors with url

internal/api_ui/server_test.go, internal/repositories/connections.go, internal/repositories/ftsutil.go, internal/repositories/ftsutil_test.go, internal/repositories/tests/connections_test.go
Allow searching for connections writing only some of the chars of a did.
=> feat: Filter connections by substrings of a did.

docs/examples/schemas/json-ld/exampleBoolean.json-ld, docs/examples/schemas/json-ld/exampleDate.json-ld, docs/examples/schemas/json-ld/exampleEmployee.json-ld, docs/examples/schemas/json-ld/exampleInteger.json-ld, docs/examples/schemas/json-ld/exampleNumber.json-ld, docs/examples/schemas/json-ld/exampleString.json-ld, docs/examples/schemas/json/exampleBoolean.json, docs/examples/schemas/json/exampleDate.json, docs/examples/schemas/json/exampleEmployee.json, docs/examples/schemas/json/exampleInteger.json, docs/examples/schemas/json/exampleNumber.json, docs/examples/schemas/json/exampleString.json
updating schema examples paths due to repo renaming
=> docs: updating schema examples

internal/api_ui/server_test.go, internal/repositories/claims.go
=> feat: Partial did search in get credentials.

ui/package-lock.json, ui/package.json
The version is not used, as this is not an independent module. Therefore it should be wholly dependent on the repo's release versioning.
The changes in `package.json-lock` were effectuated only by deleting it and running `npm i` again. This cleared the vulnerabilities.
=> fix: UI package alignments & 1 high-severity vulnerability

Dockerfile-arm
* With this change we are reducing the docker image size from 3gb to 600mg in arm64 architectures.
=> chore: update Dockerfile-arm.

Dockerfile-arm, cmd/issuer_initializer/main.go, cmd/notifications/main.go, cmd/pending_publisher/main.go, cmd/platform/main.go, cmd/platform_ui/main.go, internal/config/config.go
If vault or did env vars are not set, we will try to download from the mounted volume we use in k8s configuration. If not found we will fail.
=> Load token vault and did from k8s mounted volume

go.mod, go.sum, internal/log/log.go
Upgrading slog experimental library to use latest changes in slog library.
Suggested by https://github.com/0xPolygonID/issuer-node/pull/420
=> chore: Update slog library

.github/workflows/dockerhub-dev.yml, .github/workflows/dockerhub-main.yml
* Update action for develop branch
* Crate a new action for main branch
=> Update docker hub actions

internal/api_ui/server_test.go, internal/core/services/claims.go, internal/jsonschema/schema.go, internal/loader/w3CDocumentLoader.go, internal/loader/w3CDocumentLoader_test.go, pkg/schema/schema.go
* Implement a w3c document loader to avoid fetching documents from an external source
=> chore: add w3c loader

ui/src/components/credentials/IssueCredentialForm.tsx, ui/src/styles/theme.ts
=> fix: Fix a bug making form values to be removed after typing

api_ui/api.yaml, internal/api_ui/api.gen.go, internal/api_ui/server.go, internal/api_ui/server_test.go, internal/core/ports/connections_repository.go, internal/core/ports/connections_service.go, internal/core/ports/identity_service.go, internal/core/services/connections.go, internal/core/services/identity.go, internal/db/schema/migrations/202311211436040_add_user_authentications_table.sql, internal/db/tests/connections_fixture.go, internal/repositories/connections.go, internal/repositories/tests/connections_test.go
=> feat: adding authentication session

api_ui/api.yaml, internal/api_ui/api.gen.go, internal/api_ui/responses.go, internal/api_ui/server.go, internal/api_ui/server_test.go, internal/core/ports/claims_repository.go, internal/core/ports/claims_service.go, internal/core/ports/connections_repository.go, internal/core/ports/connections_service.go, internal/core/services/claims.go, internal/core/services/connections.go, internal/repositories/claims.go, internal/repositories/connections.go, internal/repositories/tests/claims_test.go, internal/repositories/tests/connections_test.go, pkg/pagination/pagination.go
this PR enables pagination in the getConnections endpoint, same implementation as in the getCredentials
=> feat: adding paging to the getConnections endpoint

cmd/notifications/main.go, cmd/platform_ui/main.go, internal/api_ui/responses.go, internal/api_ui/server_test.go, internal/core/ports/claims_repository.go, internal/core/ports/connections_repository.go, internal/core/ports/connections_service.go, internal/core/services/connections.go, internal/core/services/tests/notification_test.go, internal/repositories/claims.go, internal/repositories/connections.go, internal/repositories/tests/connections_test.go
Pagination in connections was failing due to a some incompatibilities with tables joins and offset limit implementation.
=> fix: Pagination in connections 

ui/src/adapters/api/connections.ts, ui/src/adapters/api/credentials.ts, ui/src/adapters/api/index.ts, ui/src/adapters/parsers/index.ts, ui/src/adapters/parsers/view.ts, ui/src/components/connections/ConnectionsTable.tsx, ui/src/components/credentials/CredentialsTable.tsx, ui/src/components/credentials/IssuanceMethodForm.tsx, ui/src/components/credentials/IssueCredential.tsx, ui/src/components/credentials/IssueCredentialForm.tsx, ui/src/utils/constants.ts
This PR implements remote sorting for the tables Credentials and Connections.
=> feat: Implement remote sorting for Credentials and Connections

api/api.yaml, internal/api/api.gen.go, internal/api/responses.go, internal/api/state.go, internal/api/state_test.go, internal/api_ui/responses.go, internal/api_ui/server.go, internal/core/ports/identity_service.go, internal/core/ports/identity_state_repository.go, internal/core/services/identity.go, internal/repositories/identity_state.go
Add pagination for identity state transactions
=> Identity State transactions pagination

api/api.yaml, internal/api/api.gen.go, internal/core/domain/link.go, internal/core/services/link.go
=> fix: deeplink and universallink fields in link response are always present

internal/payments/settings.go, internal/payments/settings_test.go, internal/payments/testdata/payment_settings.test.yaml, payment_settings.sample.yaml
added `Decimals` filed to payment_config
=> feat: payment decimals

.github/workflows/autoclose_stale_issues.yml
=> Stops bugs and enhancements from becoming stale
