0xPolygonID/issuer-node

internal/core/domain/claim.go, internal/core/services/claims.go, internal/core/services/identity.go, internal/core/services/schema.go, internal/db/schema/migrations/20230309164801_update_claims_mtp_proof_column.sql
Iden3SparseMerkleProof was deprecated and updated with Iden3SparseMerkleTreeProof
Libraries updated:
https://github.com/iden3/go-merkletree-sql/releases/tag/v2.0.2
https://github.com/iden3/go-iden3-crypto/releases/tag/v0.0.14
https://github.com/iden3/go-iden3-core/releases/tag/v1.0.1
https://github.com/iden3/go-schema-processor/releases/tag/v1.1.2
=> chore: moving from Iden3SparseMerkleProof to Iden3SparseMerkleTreeProof

.github/CODEOWNERS
Change the code owners file to better fit  backend and frontend teams workflow.
Backend team members will be automatically placed as code reviewers for any PR that affects backend folders and root files.
Frontend team members will be code owners of /ui folder
=> Code Owners proposal

internal/api/server_test.go, internal/api_admin/server_test.go, internal/core/services/claims.go, pkg/pubsub/mock.go
We will send this notification when it is confirmed that is saved in the blockchain
=> Do not throw CreateCredential event for mtProof credentials

api_ui/api.yaml, internal/api_admin/api.gen.go, internal/api_admin/responses.go, internal/api_admin/server_test.go, internal/core/services/tests/link_test.go
Affected endpoints:
* Get Credential
* Get Connections
* Get Connection
rename:
`Returns the list of links to credentials` for `Get Links`
=> chore: renaming credential attributes for credential subject

internal/core/services/identity.go, internal/repositories/connections.go, internal/repositories/tests/connections_test.go
* Send push notifications only when a connection is created, not when updated
* Ensures that push notification token is updated when the connection is updated
=> feat: avoid sending notifications when updating connections

internal/api/server.go, internal/api_ui/server.go, internal/core/services/claims.go, pkg/schema/schema.go
example of improvement:
Creating a credential where the credentialSubject does not match the given schema:
**previous error:**
```
{
"message": "cannot process schema"
}
```
**current error**
```
{
"message": "credential subject does not match the provided schema"
}
```
=> chore: improving create credential errors

internal/api_ui/server.go, internal/api_ui/server_test.go, internal/core/services/link.go
This PR contains the validation of a link in order to generate a qr code. Invalid links will cause a 404 error
Definition of invalid link:
1. Link is not active
2. Link has reached the maximum amount 
3. Link is expired
=> fix: returning an error when trying to create qr code for invalid link

internal/repositories/claims.go
This PR solves the error for publish state | retry publish state.
> "number of field descriptions must equal number of destinations, got 19 and 20"
=> fix: publish state

internal/core/services/claims.go
previous format:  {host}/v1/{issuerDID}/claims/{claimID} 
expected format: {host}/v1/credentials/{credentialID}
=> fix: wrong verifiable credential id in api-ui

internal/core/services/tests/notification_test.go
Noticed this duplicated subtest while exploring the codebase.
=> chore: Remove duplicated notification subtest: 'should get an error,wrong credential id'

cmd/platform_ui/main.go, internal/api_ui/server_test.go, internal/core/services/link.go, internal/core/services/tests/link_test.go, internal/jsonschema/schema.go, internal/jsonschema/schema_test.go
The credential validator when creating links was failing with IPFS schemas
=> fix: IPFS schemas not accepted when creating links

internal/core/services/identity.go
solving error while trying to create a connection (link issuance) -> `\u0000 cannot be converted to text.`
=> fix: cannot create connection with empty unicode fields

README.md
The step to install the issuer node in local mode setup was wrong. The command to compile the binaries locally is 
`make build-local` and not make build.
=> fix: How to build locally typo

api_ui/api.yaml, internal/api_ui/api.gen.go, internal/api_ui/server.go, internal/api_ui/server_test.go, internal/core/domain/schema.go, internal/core/ports/schema_service.go, internal/core/services/tests/link_test.go, internal/core/services/tests/schema_test.go, internal/db/schema/migrations/202307111216560_update_schemas_version_title_column.sql, internal/repositories/schema.go, internal/repositories/tests/schema_test.go
as required, we made optional the title and description fields in the schema import so as it is in the get schema and get schemas endpoints
=> feat: making title and description nullables in schemas

cmd/platform/main.go, cmd/platform_ui/main.go, internal/core/services/claims.go, internal/core/services/revocation.go, pkg/reverse_hash/reverse_hash.go
In order to enable the RHS:
1. Enable it in the .env-issuer -> ISSUER_REVERSE_HASH_SERVICE_ENABLED=true
2. Install the RHS -> https://github.com/iden3/reverse-hash-service
3. ISSUER_REVERSE_HASH_SERVICE_URL= {RHS url}
=> feat: enabling RHS in the api and  api-admin

Makefile, README.md, ui/scripts/deploy.sh
This PR fixes:
* A bug that prevented the service `issuer-ui` from starting after it was stopped.
* A broken link in the readme.
=> Fix issuer UI restart

ui/src/components/shared/SettingsModal.tsx
This PR adds a page reload warning to the IPFS gateway modal:
=> feat: Add config reload banner

cmd/notifications/main.go, internal/core/event/event.go, internal/core/ports/claims_repository.go, internal/core/ports/claims_service.go, internal/core/ports/notification_service.go, internal/core/services/claims.go, internal/core/services/notification.go, internal/gateways/publisher.go, internal/repositories/claims.go, pkg/notifications/messages.go
waiting for mobile implementation
16-01 -> Already tested with mobile and working
=> feat: adding revoke push notification

api/api.yaml, api_ui/api.yaml, internal/api/api.gen.go, internal/api/server.go, internal/api_ui/api.gen.go, internal/api_ui/server.go, internal/api_ui/server_test.go, internal/core/domain/claim.go, internal/core/services/claims.go
avoid fetching credential QR Codes for empty mtp proofs credentials. 
Returns a 409 conflict when the proof is empty (suggest a code)
=> chore: avoid fetching credentials with empty mtp proofs

internal/jsonschema/schema.go
As part of the link creation we validate that a VC can be produced with the provided schema and credential Subject. New Schemas include a new type property inside the credential Status that has to be added to the dummy VC
=> fix: could not create links with new type property in credential status

internal/core/services/identity.go, internal/core/services/tests/identity_test.go, internal/gateways/publisher.go, internal/repositories/claims.go
* Fix and improve the publish state process.
=> fix: publish state and improve performance when processing takes place

internal/api_ui/server_test.go, internal/core/services/identity.go, internal/core/services/link.go
avoid sending null scope in qr codes
=> fix: avoid sending null scope

cmd/issuer_initializer/main.go
* Fix revocation status direct URL when issuer DID is generated running `make generate-issuer-did`
=> fix: revocation status url

k8s/helm/templates/_helpers.tpl, k8s/helm/values.yaml
Updates Reverse Hash Service OnChain Contract
=> fix: Reverse OnChain Contract updated

internal/core/services/link.go
If only one error is used, when the first value of "err" is not nil and second value of "err" is nil, there may be a situation that "the function execution should marked as failed, but it returns nil"
=> add separate error variable for setLink()

k8s/helm/values.yaml
There are some invisible characters in this value, which causes the url to have `%E2%80%8D` after amoy
=> fix: invisible characters

api/api.yaml, internal/api/api.gen.go, internal/api/server.go, internal/api/server_test.go, internal/api_ui/server.go, internal/api_ui/server_test.go, internal/core/ports/claims_service.go, internal/core/services/link.go, internal/core/services/tests/identity_test.go, internal/core/services/tests/link_test.go
* Add proofs field to the create claim body endpoint in core API.
* The values allowed are:  BJJSignature2021┃Iden3SparseMerkleTreeProof
With this feature the user can specify the type of proof for the claim
=> chore: add proofs to create claim endpoint

infrastructure/local/docker-compose-infra.yml, k8s/helm/readme.md, k8s/helm/templates/_helpers.tpl, k8s/helm/templates/issuer-node-api-configmap.yaml, k8s/helm/templates/issuer-node-api-deployment.yaml, k8s/helm/templates/issuer-node-api-ui-deployment.yaml, k8s/helm/templates/issuer-node-notifications.yaml, k8s/helm/templates/issuer-node-pending-publisher.yaml, k8s/helm/templates/issuer-node-ui-configmap.yaml, k8s/helm/templates/issuer-node-ui-deployment.yaml, k8s/helm/templates/postgres-deployment.yaml, k8s/helm/templates/redis-deployment.yaml, k8s/helm/templates/vault-deployment.yaml, k8s/helm/values.yaml
* Add support for custom did methods in Helm chart
* improve service account definition
=> chore: add custom did methods

.env-issuer.sample, Makefile, README.md, cmd/kms_local_storage_priv_key_importer/main.go, cmd/platform/main.go, infrastructure/local/docker-compose.yml, internal/config/config.go, internal/core/services/identity.go, internal/kms/kms.go, internal/kms/local_storage_bjj_key_provider.go, internal/kms/local_storage_eth_key_provider.go, internal/kms/local_storage_utils.go, internal/kms/local_storage_utils_test.go, internal/kms/vault_bjj_key_provider.go, internal/kms/vault_eth_key_provider.go, internal/kms/vault_providers_helpers.go
Now the issuer node can be run without using the vault, saving the private keys in a file, which is useful for local and/or testing environments.
* The`ISSUER_KMS_PLUGIN` environment variable allows you to specify the type of storage for private keys. Accepts the values ​​"localstorage" and "vault.
* Added a new command in the make file to run the infrastructure (postgres and redis) without vault: `make up/localstorage`
* To add the private key to the localstorage a new command was added: `make private_key=4b3XXX add-private-key-localstorage`
=> chore: add kms local storage

.github/workflows/golangci-lint.yml, api/api.yaml, internal/api/api.gen.go, internal/api/server.go, internal/api/server_test.go, internal/core/services/identity.go, internal/db/tests/claims_fixture.go
This PR duplicate old "claims" endpoints in core API renaming it to "credentials". Old claims endpoints remains untouched but marked as deprecated.
=> feat: Rename claims endpoints to credential endpoints

.github/workflows/checks.yml, api/api.yaml, cmd/platform/main.go, internal/api/api.gen.go, internal/api/connections.go, internal/api/credentials.go, internal/api/credentials_test.go, internal/api/identity.go, internal/api/identity_test.go
- added GET /credentials/search endpoint with FTS and pagination
- added DELETE /credentials/{id} endpoint
- added PATCH AllowedMethod to CORS settings
- extend GET /identities with `authBJJCredentialStatus`, `method`, `blockchain` and `network`
=> feat: add paginated credentials, delete credential endpoinst, PATCH method to CORS

api/api.yaml, internal/api/api.gen.go, internal/api/identity.go, internal/api/identity_test.go, internal/api/networks.go, internal/api/networks_test.go, internal/core/domain/identity.go, internal/core/ports/identity_repository.go, internal/core/ports/identity_service.go, internal/core/services/identity.go, internal/db/schema/migrations/202408091258180_add_display_name_to_identities_table.sql, internal/db/tests/fixture.go, internal/db/tests/identity_fixture.go, internal/repositories/identity.go, pkg/network/resolver.go
- Added `DisplayName` field to Identity table
- Updatet CreateIdentity endpoint with new field
- Added UpdateIdentityDisplayName endpoint with possibility to change new field
- Added new endpoint which returns supported (registered) blockchains/networks
=> feat: Identity Display Name and supported chain/networks endopoint

internal/api/responses.go
=> fix: Rename proof type SparseMerkleTreeProof to Iden3SparseMerkleTree in all API

internal/api/credentials.go, internal/api/credentials_test.go, internal/core/services/claims.go
=> fix: Return 400 when credential subject id is wrong on create credential

internal/core/services/payment.go
- The IsPaymentDone contract call should pass the signer address (the one recovered from the signature) as the first parameter, not the Recipient address.
- Refactor the payment verification process to simplify it.
=> fix: verify payment

api/api.yaml, internal/api/api.gen.go, internal/api/payment.go, internal/api/responses.go, internal/core/domain/payment.go, internal/core/ports/payments_repository.go, internal/core/services/payment.go, internal/db/schema/migrations/2025012711184901_add_status_to_payment_request.sql, internal/repositories/payment.go
- added `modifiet_at`, `status`, `paid_nonce` to `payment_requests` table
- update these fields on payment verification
- if status is `success`, than `paid_nonce` is not empty
=> feat: payment requests status
